import {Barlow, DM_Sans, Hanken_Grotesk} from "next/font/google"
import Head from "next/head";
import "./globals.css";

export const dm_sans = DM_Sans({
    subsets: ["latin"],
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
    variable: "--font-dm_sans",
});
export const hanken = Hanken_Grotesk({
    subsets: ["latin"],
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
    variable: "--font-hanken",
});

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
     

      <body className={` ${hanken.className} antialiased `} suppressHydrationWarning>
        {children}
      </body>
    </html>
  );
}
